### PR TITLE
Master branch

### PR DESCRIPTION
**Pull request by itsmeshibintmz**
for snake animation graph

### CODE REVIEW

**Comment by itsmeshibintmz** [comment]
It didn't create the pull request as I expected.

**Comment by itsmeshibintmz** [comment]
I've added the snake contribution graph as like you can see on my profile, but couldn't merge it. Hope you can figure out how to add it to your profile through my profile, if need any assistance, feel free to ask.

**Comment by max0700** [comment]
Please

**Comment by max0700** [comment]
Do you resolve it.

**Pull request closed without merging**
